image: node:4.2.2

pages:
  cache:
    paths:
    - node_modules/
    
  script:
  - npm config set loglevel warn
  - npm install hexo-cli -g
  - npm install hexo --save
  - npm install
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - master
