image: mcr.microsoft.com/dotnet/core/sdk:2.2

pages:
  cache:
    paths:
    - /root/.nuget/packages
    
  script:
  - export PATH="$PATH:/root/.dotnet/tools"
  - dotnet tool install fake-cli -g
  - rm -rf ./.fake
  - fake build
  artifacts:
    paths:
    - public
  only:
  - master
