image: mcr.microsoft.com/dotnet/core/sdk:6

pages:
  script:
  - export PATH="$PATH:/root/.dotnet/tools"
  - dotnet tool install fake-cli -g
  - rm -rf ./.fake
  - fake build
  artifacts:
    paths:
    - public
  only:
  - master
