title = "Arthur Rump"
author = "Arthur Rump"
author-twitter = "@arthurrump"
profile-image = "/profile/profile_full_256.jpg"
description = "Tells computers what to do. Makes things. Studies Computer Science and Science Education."

# Social image used for posts without an header image
default-image = "/icon_512.png"

disqus-id = "arthurrump"

[[nav]]
name = "Blog"
url = "/"
[[nav]]
name = "Projects"
url = "/projects"
[[nav]]
name = "Research"
url = "/research"
[[nav]]
name = "About me"
url = "/about"

[[social-links]]
name = "GitHub"
icon = "github"
url = "https://github.com/arthurrump"
[[social-links]]
name = "YouTube"
icon = "youtube"
url = "https://www.youtube.com/channel/UCUTcNWxjKLUj9JFyHvaynCQ"
[[social-links]]
name = "Vimeo"
icon = "vimeo"
url = "https://vimeo.com/arthurrump"
# [[social-links]]
# name = "Mastodon"
# icon = "mastodon"
# url = "https://mastodon.utwente.nl/@arthurrump"
[[social-links]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/arthurrump"
[[social-links]]
name = "Keybase"
icon = "keybase"
url = "https://keybase.io/arthurrump"
[[social-links]]
name = "NuGet"
icon = "nuget"
url = "https://www.nuget.org/profiles/arthurrump"
[[social-links]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/arthurrump"
[[social-links]]
name = "StackOverflow"
icon = "stackoverflow"
url = "https://stackoverflow.com/story/arthurrump"
[[social-links]]
name = "Reddit"
icon = "reddit"
url = "https://www.reddit.com/user/arthurrump"
[[social-links]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/arthurrump"