# Menus
menu:
  Home: .
  Archives: archives
  About: about

# Customize
customize:
    logo:
        enabled: false
        width: 40
        height: 40
        url: 
    profile:
        enabled: false # Whether to show profile bar
        avatar: 
        gravatar: arthurrump@outlook.com
        author: Arthur Rump
        author_title: C# Developer for Windows and the Web
        location: Groningen, the Netherlands
        follow: https://twitter.com/arthurrump/
    highlight: monokai
    sidebar: right # sidebar position, options: left, right
    thumbnail: false # enable posts thumbnail, options: true, false
    favicon: # path to favicon
    social_links:
        github: https://github.com/arthurrump
        gitlab: https://gitlab.com/arthurrump
        twitter: https://twitter.com/arthurrump
        rss: /feed.xml
    social_link_tooltip: false # enable the social link tooltip, options: true, false

# Widgets
widgets:
    - recent_posts
    - category
    #- archive
    - tag
    #- tagcloud
    - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus: arthurrump # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    google_analytics: # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code
    baidu_analytics: # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        Twitter: https://twitter.com/arthurrump
        GitHub: https://github.com/arthurrump
        GitLab: https://gitlab.com/arthurrump
        RSS: /feed.xml
